window.KNOWN_STATS = {
  totalDays: 100,
  dateRange: '10 Feb 2001 – 20 May 2001',
  trainingPosts: 89,
  restOrNoWod: 11,
  literalNoWodDays: 1,
  readingResourceDays: 91,
  rowingDays: 26,
  runningDays: 13,
  bikingDays: 11,
  swimDays: 6,
  benchDays: 17,
  ropeClimbDays: 7,
  muscleUpDays: 6,
  tabataDays: 4,
  duplicateConsecutiveWorkoutDates: '20–21 Apr 2001',
  toesToBarDescriptionDays: 6,
  appStoreLinks: 2
};

window.FIRST100_DAYS = [
  "2001-02-10","2001-02-11","2001-02-12","2001-02-13","2001-02-14","2001-02-15","2001-02-16","2001-02-17","2001-02-18","2001-02-19","2001-02-20","2001-02-21","2001-02-22","2001-02-23","2001-02-24","2001-02-25","2001-02-26","2001-02-27","2001-02-28","2001-03-01","2001-03-02","2001-03-03","2001-03-04","2001-03-05","2001-03-06","2001-03-07","2001-03-08","2001-03-09","2001-03-10","2001-03-11","2001-03-12","2001-03-13","2001-03-14","2001-03-15","2001-03-16","2001-03-17","2001-03-18","2001-03-19","2001-03-20","2001-03-21","2001-03-22","2001-03-23","2001-03-24","2001-03-25","2001-03-26","2001-03-27","2001-03-28","2001-03-29","2001-03-30","2001-03-31","2001-04-01","2001-04-02","2001-04-03","2001-04-04","2001-04-05","2001-04-06","2001-04-07","2001-04-08","2001-04-09","2001-04-10","2001-04-11","2001-04-12","2001-04-13","2001-04-14","2001-04-15","2001-04-16","2001-04-17","2001-04-18","2001-04-19","2001-04-20","2001-04-21","2001-04-22","2001-04-23","2001-04-24","2001-04-25","2001-04-26","2001-04-27","2001-04-28","2001-04-29","2001-04-30","2001-05-01","2001-05-02","2001-05-03","2001-05-04","2001-05-05","2001-05-06","2001-05-07","2001-05-08","2001-05-09","2001-05-10","2001-05-11","2001-05-12","2001-05-13","2001-05-14","2001-05-15","2001-05-16","2001-05-17","2001-05-18","2001-05-19","2001-05-20"
];

// Full verbatim first 100 CrossFit.com entries, 10 Feb 2001 through 20 May 2001.
// Entry text is embedded locally so the GitHub Pages site works without runtime fetching.
window.FIRST100_ENTRIES = [
  {
    "date": "2001-02-10",
    "text": "For time:\nFast & Heavy\nDumbell \"Thruster\" 21 reps\nRun 1/4 mile (400m)\nDumbell \"Thruster\" 18 reps\nRun 1/4 mile (400 m)\nDumbell \"Thruster\" 15 reps\nRun 1/4 mile (400 m)\n\nNotes:\n\"Thruster\" is a deep front squat to a push press all in one explosive movement.\nTime routine from start to finish.\nRanking is a composite of load used in \"Thruster\" and total time.\nSubmit body weight because load value is based on percentage of body weight."
  },
  {
    "date": "2001-02-11",
    "text": "Dumbbell deadlift 10 reps\nHang from pull-up bar and slowly curl body until toes touch the bar 15 reps\nDumbell deadlift 8 reps\nHang from pull-up bar and slowly curl body until toes touch the bar 15 reps\nDumbell deadlift 6 reps\nHang from pull-up bar and slowly curl body until toes touch the bar 15 reps\nDumbell deadlift 4 reps\nHang from pull-up bar and slowly curl body until toes touch the bar 15 reps\nDumbell deadlift 2 reps\nHang from pull-up bar and slowly curl body until toes touch the bar 15 reps\nCycle two minutes at high resistance\nCycle two minutes at high RPM\nCycle two minutes at high resistance\n\nNotes:\nIncrease the deadlift weight each set.\nMaintain perfect form or you'll cripple yourself.\nCycle effort is all out; this is not a cruise.\nOn the bar-toe touch, move in slow motion, i.e, no swing at all.\n\nLook at the Clean & Jerk and Snatch performed by a champion, frame by frame.\nNotice that he is not pulling the bar up his body, but pulling himself to the bar.\nNotice, also, the elbows pointed straight ahead in the racked position (tremendous flexibility).\n\nFinally, given that each frame represents an even time interval, make some\nevaluations as to where the quickest movements occur.\nhttp://www.eng.auburn.edu/users/simonton/wl/cj.html"
  },
  {
    "date": "2001-02-12",
    "text": "Today's workout is a simple yet elegant whole body circuit.\nThirty reps of 20 lb. Medicine ball squats.\n30 reps assisted pull-ups with 1/2 your body weight as assistance.\nRepeat at 25, 20, 15, and 10 reps for a total of five rotations.\nRecord and report your total time for all five rotations.\n\nFASTEST TIME TAKES IT!\nTake a prolonged stretching warm-up and cool-down.\n\nThe Eades' book Protein Power is a classic in responsible nutrition.\nPublishers of best selling books are typically not interested in publishing\nthe author's bibliography. Here are the foundations for Protein Power.\nNext time someone tells you that reduced carbohydrate diets are fads\nwith no scientific basis ask them if they've read any of the hundreds of\nscholarly works cited by Michael and Mary Dan Eades.\n[http://www.eatprotein.com/bib paper.html ](http://www.eatprotein.com/bib paper.html )"
  },
  {
    "date": "2001-02-13",
    "text": "1) \"Warm Up\": Bike 20 minutes at a warm-up pace.\nWe are doing three sets of back squats at twenty-one reps each.\nChoose a weight that you feel you can handle comfortably for\ntwenty-one reps of regular back squats. These specialized movements\nare tough! Make damned sure you warm-up thoroughly with \"air squats\"\nand stretching first.\n2) \"Power squat\": Lower and rise as quickly as you can while maintaining\nPERFECT form. Repeat 20 times.\n3) \"Bottom to bottom\": Lower to full squat position (thighs parallel to floor),\nhold for a full ten seconds, rise and immediately upon full extension of hip\nand leg return to bottom and hold for ten seconds. Repeat 20 times.\n4) \"Super slow\": Take twenty seconds to reach bottom and twenty seconds\nto reach top again. Repeat 20 times.\n5) Finally, how long can you maintain a 2:00 min. 500-meter pace average?\nSet the rower for \"Avg 500 meter pace\" and stop and record the time at the\ninstant you fall under the 2:00 minute average (2:00 for men and 2:10 for women).\nEmail your squat and row time to feedback@crossfit.com."
  },
  {
    "date": "2001-02-14",
    "text": "On Monday we worked gymnastics/calisthenic movements, on Tuesday we worked\nmetabolic conditioning with a short, middle, and long distance effort, Wednesday we\nworked through some of the classics of weightlifting and weight training. Today we\nare taking a day of active rest. If you’ve performed to expectation you’ll welcome the\nbreak. If you know our methods, you'll make an intelligent inference about tomorrow (hint).\n\nThe idea here is to engage in some sport or activity at intensity above recreational while\nbeing below our regular training intensity. Don't count your primary sport! This is a\ncross-training opportunity. Step outside your normal bounds. Below are some suggestions.\n\nBicycle Hill Climb\nHoops! (Basketball)\nSwimming\nMountain Hike\nRollerblade\nSurf Paddle\nHandball or racquetball\nTennis\n\nLet us not be content to wait and see what will happen, but give us the\ndetermination to make the right things happen.\n~ Peter Marshall ~\n(1902-1949, American Presbyterian Clergyman)\n\nThe bench press is a classic exercise. Though overvalued in popular lore\nit is still without a doubt indispensable to your weight training program. Here\nis an article on bench press technique from a champion and coach of\nchampions, Dave Tate, of Westside Barbell Club, an epicenter of Powerlifting\nachievement.\nhttp://www.testosterone.net/html/body_115b600.html"
  },
  {
    "date": "2001-02-15",
    "text": "How far can you continue this sequence within one hour?\nIf you can't do the push-ups, do them from the knees.\nIf you can't do the pull-ups, do them with half your body weight as assistance.\n\nRankings are separate for those doing either assisted pull-ups or push-ups from the knees.\n\nHere is a report on a guy who has nearly stumbled on the CrossFit formula.\nCheck it out. The site hosting the article is a fun and fairly reliable site for\nfitness info.\nhttp://www.cbass.com/EvolutionaryFitness.htm"
  },
  {
    "date": "2001-02-16",
    "text": "Find your best back squat at 5,3, and 1 reps\nFind your best deadlift at 5,3, and 1 reps\nFind your best bench-press at 5,3, and 1 reps\n\nSubmit your total weight lifted in all nine sets along with your bodyweight.\nRankings are based on total weight divided by body weight.\n\nThere is an internationally recognized sport based on the three lifts\nfrom today's routine. That is the sport of Powerlifting. Today's link is a\ngood resource for information on powerlifting.\nhttp://www.powerlifting.com/training.cfm"
  },
  {
    "date": "2001-02-17",
    "text": "Rope climb and do push-ups non-stop for 30 minutes.\nThe objective here is to climb and push until you can do neither.\nThoroughly exhaust both functions within 30 minutes.\nReport the details of the experience both today and the effects tomorrow.\n\nCount the number of trips up the rope (the CrossFit rope is a 13' \"shorty\")\nand the number of push-ups within the half hour. Remember the CrossFit\npush-up is a very rigid body, deep, controlled movement.\nNo cheating on the push-up!!\n\nFind a swimming hole/pool and pound out 15 fast laps!!\n\nRope climb is functional and arguably the ultimate pulling movement\nand yet the exercise is nearly extinct except for police and military training.\n\nToday's link takes us back to Clarence Bass' site for a primer on soreness.\nRemember, though Mr. Bass' site is very good his emphasis is body building\nand not athletic performance.\nhttp://www.cbass.com/soreness.htm"
  },
  {
    "date": "2001-02-18",
    "text": "Jump rope for two minutes rest for one minute.\nCan you continue this for thirty minutes?\nThis is just twenty minutes of cardiovascular exercise.\nGo for it!! If you have considerable jump rope experience,\n\"double under\" for two minutes rest for one.\nAnyone who can keep this up for thirty minutes is an extraordinary athlete.\n\nJumping or skipping rope is a good tool for developing cardiovascular and\nrespiratory endurance, stamina, coordination, agility, accuracy, and balance.\n(This is six of the ten adaptive components.)\n\nHere is a simple little site that reviews some of the basic to advanced jump rope\nskills that you want to play with.\nhttp://tqjunior.thinkquest.org/5407/index.shtml"
  },
  {
    "date": "2001-02-19",
    "text": "Row 4000 meters @ a 2 min 500 meter pace\nWithin the next 16 mins hang clean 50% of your body weight 21 times\n\nRow 2000 meters @ a 2 min 500 meter pace\nWithin the next 8 mins hang clean 50% of your body weight 18 times\n\nRow 1000 meters @ a 2min 500 meter pace\nWithin the next 4 mins hang clean 50% of your body weight 15 times\n\nRow 500 meters @ a 2 min 500 meter pace\nWithin the next 2 mins hang clean 50% of your body weight 12 times\n\nThere's no rest here other than the time allowed for the hang clean.\nNot everyone can make the numbers, do what you can safely, effectively.\n\nToday's link is an article by Dr. Steven Seiler, a noted researcher, and renowned rowing coach.\nThe article is called \"The Time Course of Training Adaptations.\"\nIt is recommended that you read and reread the article until you fully understand it.\n\nThe physiology that Dr. Seiler details contains the very reason endurance\nwork must be limited for athletes that don't specifically compete at long distances.\nhttp://home.hia.no/~stephens/timecors.htm"
  },
  {
    "date": "2001-02-20",
    "text": "Bike 5 mins hard.\nDumbbell Bench-press 15 reps.\n\nBike 5 mins hard.\nDumbbell Bench-press 15 reps.\n\nBike 5 mins hard.\nDumbbell Bench-press 15 reps.\n\nAfter a warm-up make your first effort a heroic effort on the bike\nand record the distance. Take any rest needed and give the best\ndumbbell bench-press you can at fifteen reps or less. Again, rest\nas long as you want then repeat both efforts. Use the same\nweight for each bench press set.\n\nIf the first cycling and bench-press effort are true max efforts, then\nthe second and third efforts are not repeatable no matter how long the rest.\n\nTo test the quality of the first efforts and demonstrate the point of the\nworkout take a LONG break after each couplet.\n\nKeep the rest between cycle effort and bench-press constant for each couplet.\n\n\"Superficial goals lead to superficial results.\"\nAttila the Hun\n\nHere is Dr. Seiler on breathing. It's a great and thorough exploration of the subject: http://home.hia.no/~stephens/ventphys.htm"
  },
  {
    "date": "2001-02-21",
    "text": "Row 500 meters\nRest as needed\nDeadlift max at 15 reps, immediately on last rep, come up and...\nMax set of pull-ups.\nRest as needed.\nRepeat deadlift set again, come up immediately on last rep and...\nMax set of pull-ups.\nRest as needed.\nRepeat deadlift set again, come up immediately on last rep and...\nMax set of pull-ups\nRest as needed.\nRow 500 meters\n\n\"Hard training, easy combat; easy training, hard combat\" -\nMarshal Suvorov -\nfamous Russian General who understood training specificity.\n\nCan anyone explain why the essence of this program\n(http://call.army.mil/call/nftf/janfeb97/bfpt.htm )\nis consistent with the CrossFit Program?"
  },
  {
    "date": "2001-02-22",
    "text": "You deserve a break today!! IT'S AEROBIC DAY!\n\nToday's workout is a long (1/2 hour +), slow (low intensity),\nrecreational (keep it fun) effort. Bike, Run, Swim, or Row.\nThis is an active rest for any accomplished athlete. If you'd itch for\nsome additional work, do some ab work. Otherwise, take it easy.\n\n\"Bodily exercise, when compulsory, does no harm to the body; but knowledge\nwhich is acquired under compulsion obtains no hold on the mind. \"\nPlato, The Republic\n\nHere's a site for mid-distance running.\nhttp://run-down.com/training \nMid-distance running is anaerobic work. Anaerobic work comprises the bulk\nof athletic training and yet it is tragically neglected by gyms, trainers, popular\nmagazines, and the general public. This ignorance can be demonstrated\nquantitatively, to wit: We did a search for \"anaerobic training\" on Alta Vista\nand came up with 17 hits for the term, when we repeated this for \"aerobic\ntraining\" I found 14,598 hits.\n\nInterestingly, the popular (gyms, magazines, internet, etc.) ignorance of\nanaerobic training is not shared by professional sports, or NCAA Div 1\nUniversity Programs and of course CrossFit."
  },
  {
    "date": "2001-02-23",
    "text": "Hollow Rock for 1 Minute\n(Lie on your back, place your arms overhead, and rock smoothly\nback and forth like a rocking chair.)\nArch Rock for 1 Minute\n(Lie on your stomach, place your arms overhead, lift your heels\nwith straight legs, and rock smoothly back and forth like a rocking chair.)\nTen one legged squats, left leg\n(Hold your jump rope strung over your pull-up bar for balance and\nassistance if you've not developed the fitness for this yet.)\nTen one legged squats, right leg\n(Same assistance if needed.)\nRepeat the above twice for a total of three circuits.\n\n\"To exercise at or near capacity is the best way I know of reaching a\ntrue introspective state. If you do it right, it can open all kinds of inner doors.\"\nAl Oerter - 4 time Olympic Gold Medalist in Discus\n\nNo gym is complete without paralettes. The exercises done on paralettes\ncontribute immeasurably to being CrossFit. Here is a simple plan for building\nyour own pair.\n\nParallette Construction - A very useful piece of exercise equipment that can\nbe made quickly and cheaply. What you need: About 6-9 feet of PVC or ABS\npipe (decide how much you need based on the measurements below). Four\nT connections. Four elbow joints. Eight end caps. (the diameter can be\n3/4-1 1/2 in. depending on the size of the person to use the parallettes) Your\nlocal hardware store should have this great stuff.\n1. Cut two 10-14 in. pieces of pipe. (These will be the portions you hold onto)\nStick an elbow on both ends of both of these pieces.\n2. Cut four 3-8 in. pieces depending on the height you want, keep in mind the\nelbows and T joints will add to the total height. The most important part of this\nstep is to keep all these pieces the same length. Place these in the other end\nof the elbows, and attach the T joints to the free ends.\n3. Cut eight 4-6 in. pieces depending on the base width you desire. Wider is\nmore stable, but takes up more space. Place these pieces in the available slots\nin the T joints and cap the other ends. You now have parallettes.\n4. You will want to score the surface of the grip portion of the parallettes with a\nwire brush or scouring pad so that chalk will stick to itfor a better grip."
  },
  {
    "date": "2001-02-24",
    "text": "Rope Climb X 3\nBox Jump 2mins (50 jumps @ 20\" box)\n21 Dips\nBox Jump 90secs (40 jumps @ 20\" box)\n15 Dips\nBox Jump 60 secs (30 jumps @ 20\" box)\n12 Dips\nBox Jump 30 secs (20 jumps @ 20\" box)\n9 Dips\nRope Climb X 3\n\nSubmit time for completion of entire workout. Ranking requires completion of jumps\non time and at height. CrossFit rope is 13ft.\n\nThough the \"Workout of the Day\" is designed to meet the needs of elite athletes\nreadying for the highest levels of competition, they can be toned down to provide\nan acceptable challenge for even the novice exerciser. Choose lighter loads,\nreduce reps, slow the pace, and substitute one pulling, pushing, or leg exercise\nfor tamer versions of the same function. If you need help or ideas for moderating\nthese workouts let us know by email at feedback@crossfit.com\n\nThe \"Workout of the Day\" is engineered to elicit an adaptive response consistent\nwith the CrossFit philosopy (see CrossFit Foundations).\n\nFollowing the workout daily provides a substantial volume of exercise at HIGH\nintensity while minimizing the likliehood of burnout and overtraining or orthopedic\nover-stress. Considerable thought and energy has been given to the precise order\nand nature of the workouts. Alterations of this pattern potentially risks burnout,\ninjury, or gaps in your fitness.\n\n\"He's soft and he's fat and he's wearing my clothes and he's getting too old and\nhe was born on my birthday and I'm afraid if I stop running, he'll catch up with me.\"\nThe Nike poster definition of masters athlete motivation\n\nThere's reason here for incredible hope for the aging athlete. Read and rejoice!\nhttp://home.hia.no/~stephens/musage.htm"
  },
  {
    "date": "2001-02-25",
    "text": "1) Bike 20 minutes at a warm-up pace.\nWe are doing three sets of back squats at twenty-one reps each.\nChoose a weight that you feel you can handle comfortably for\ntwenty-one reps of regular back squats. These specialized movements\nare tough! Make damned sure you warm-up thoroughly with \"air squats\"\nand stretching first.\n2) \"Power squat\":\nLower and rise as quickly as you can while maintaining PERFECT form.\nRepeat 20 times.\n3) \"Bottom to bottom\":\nLower to full squat position (thighs parallel to floor), hold for a full ten\nseconds, rise and immediately upon full extension of hip and leg return to\nbottom and hold for ten seconds. Repeat 20 times.\n4) \"Super slow\":\nTake twenty seconds to reach bottom and twenty seconds to reach top\nagain. Repeat 20 times.\n5) Finally, how long can you maintain a 2:00 min. 500-meter pace average?\nSet the rower for \"Avg 500 meter pace\" and stop and record the time at the\ninstant you fall under the 2:00 minute average (2:00 for men and 2:10 for women).\n\nActions speak louder than coaches.\n(Speedo ad)\n\nHere's a good primer on VO2 max, the gold standard of aerobic fitness measurement.\nhttp://home.hia.no/~stephens/vo2max.htm"
  },
  {
    "date": "2001-02-26",
    "text": "If nobody minds, we'll give the legs a little break today-\n\nHow many pull-ups can you do in an hour?\n\nSuccess comes here by pacing and not going to failure on any set.\nRankings will be by weight class.\n\nDon't be foolish and fill in with any met-con (cardio) or other work.\nYou don't know what looms! Also, if you're current with the path\nthe other athletes have been following and your intensity has been\nworthy of your best efforts you are long overdue for a reduced\nmetabolic load.\n\nOur \"Workout of the Day\" is engineered with great dilligence to care for\nALL of your fitness needs. If some days seem too easy that is because\nworkouts either before or coming are tortuous and the backing off is\nwarranted. We are feeding you a regimen that represents the ultimate\nchallenge for the world's best athletes.\n\nIf you are concurrently training for sport, like most of our athletes, temper\nyour efforts to allow for successful sport training. This is a learned skill\nrequiring a finely honed sense of self. On the days when your sports\ntraining regimen is lighter, tear it up with our strength and conditioning\nworkout. On days when your sports training regimen is tough, moderate\nyour efforts. Many of our athletes are able to engage the \"Workout of the Day\"\nright up to and during competition by just \"going through the motions\" while\nstill \"doing\" the daily workout.\n\nAgain, the \"Workout of the Day\" is designed to accomodate additional sport\ntraining, recreational activity, or stand alone by simply modulating the intensity\nof your effort. If you need help with this concept email at feedback@crossfit.com\nand one of our coaches will gladly help you come to terms with this.\n\n\"Trample the weak. Hurdle the dead.\"\nAnonymous\n\nFred Hatfield has great instincts regarding fitness and performance.\nHe is a powerlifting champion but brings valuable insight to our concerns.\nhttp://www.drsquat.com/articles/1speed.htm"
  },
  {
    "date": "2001-02-27",
    "text": "We are due for a little circuit work. Circuit training is an excellent test\nof your overall fitness. At CrossFit intensities it becomes debilitating.\nWe use it sparingly and go all out! This is \"combat\" or \"getting out of\nthe burning building\" fitness.\n\nDecide loads and assistance (if absolutely necessary to get ALL reps)\nbefore starting. Be smart, shelve your ego and shoot for rapid completion\nwith NO rest. Submit record of total time, weights for each lift, and\nassistance (if needed on pull-ups and dips). Set up recording sheet\nahead of time. Rip!!\n\nBike for 3 miles\nTwenty ball-squats (20 lb. Med ball)\nTwenty push-ups\nTwenty pull-ups\n\nRow 500 meters\nBox step up (20\") with dumbbells, 25 right , 25 left\nBench-press 15 reps\nRope climb\n\nJump rope 200 jumps\nLunge 20 steps alternating right-left\nPush-press 15 reps\nUpright row 15 reps\n\nRun 800 meters (app. ½ mile)\nDeadlift 15 reps\nTwenty dips\nTwenty power-cleans\n\nBox Jump (20\") 50 jumps\nDumbbell \"Thruster\" (Deep front squat/push-press) 20 reps\nTwenty push-ups\nTwenty pull-ups\n\n\"Superficial goals lead to superficial results.\"\nAttila the Hun\n\nRarely does CrossFit endorse a product, though we do endorse and use the\nAbMat in our program. Today we link to the AbMat site because the science\npresented here is damned good. Scour this site thoroughly and when you are\ndone you'll know more about your abs than any trainer hanging out at the local gym.\nhttp://www.abmat.com/science.htm"
  },
  {
    "date": "2001-02-28",
    "text": "Swim leisurely for thirty minutes. Make this relaxing. If you're not a strong swimmer\nthis may be more difficult. In that case, you need the exposure.\n\nIf you are tempted to do more, either you've been loafing or you're just tuning in.\nThis is a much-needed break for the athletes in synch with the program.\n\n\"It is a sublime thing to suffer and be stronger.\"\nHenry Wadsworth Longfellow\n\nHere's a link that offers some worthwhile swimming performance links:\nwww.pponline.co.uk/\nSpeaking of swimming...For those of you following the Workout of the Day\nsteadily now, you're more than ready for a break."
  },
  {
    "date": "2001-03-01",
    "text": "Today we shift back to weightlifting.\n\nBench Press 5 sets (10,7,5,3,1 reps)\nDeadlift 5 sets (10,7,5,3,1 reps)\nRun 400 meters\nRest 5 minutes\nRun 400 meters\nRest 5 minutes\nRun 400 meters\n\nWeightlifting exercises and runs must be completed within one hour.\nReport your total weight lifted and the three 400-meter times.\n\n\"Things may come to those who wait, but only the things left by those who hustle.\"\nAbraham Lincoln\n\nHere's Dr. Hatfield describing the value of the Olympic Lifts to the athlete.\nwww.drsquat/articles/1olympic.htm"
  },
  {
    "date": "2001-03-02",
    "text": "We are ready for a break from the neurological and orthopedic stresses of\nweightlifting and hard and heavy leg work.\n\nHere is an interval that the NSCA identifies as being smack dab in the middle\nof the lactic acid metabolic pathway. Remember one of the advantages of\ninterval training is that we get extended exposure to cardiovascular work\nwithout the muscle wasting consistent with extended aerobic work.\n\nOn the Concept II Rower set up for intervals and go all out for 60 seconds\nRow easy for two minutes.\nRepeat for a total of fifteen efforts.\n\nThis is a total of forty-five minutes, yet the work is designed to enhance anaerobic\ncapacity. Now here’s the really cool part: even though this work is predominantly\nanaerobic (lactic acid pathway), it carries a heavy aerobic benefit without the\ndisadvantages of reducing speed, power, and strength known to accompany\naerobic training.\n\nOn setup scroll the display to show meters in the lower window. On your first\neffort throw as many meters up in the minute as you can. On the subsequent\nfifteen efforts fight for as much of the first distance as you can.\n\nOn completion use recall to scroll through all fifteen intervals and record and\nsubmit the meters rowed for each interval.\n\nIf you need help setting up the rower email us at feedback@crossfit.com.\nIf you don’t have access to a Concept II Rower, buy one.\n\n\"There's No Easy Way\"\nAllan Wells (1980 Olympic 100m Champion)\n\nHere is a cool site with some reasonable discussion on the benefits of\nhigh intensity training.\nhttp://www.totalcoaching.com/strength/hitsuccessseries1.html"
  },
  {
    "date": "2001-03-03",
    "text": "Rest Day\n\n\"The quality of a person's life is in direct proportion to their commitment to excellence.\"\nVince Lombardi\n\nHere's another interesting and successful approach to dieting.\nThis approach is a close cousin to the Anabolic Diet. The science here is solid.\nhttp://www.mesomorphosis.com/exclusive/mcdonald/carbup.htm\n\nWell about now you're pretty beat-up. Today is a day of active rest.\nWe want you to stretch thoroughly and participate in some recreational\nactivity, i.e., softball, basketball, mountain bike, surf, swim, etc.\n\nGet ready to fire back up on Sunday."
  },
  {
    "date": "2001-03-04",
    "text": "This is an amazingly complete workout in only twenty-four minutes.\n\nSet-up the rower for intervals of twenty seconds work and ten seconds rest.\nSet the rower to display meters in the lower window. Go all out on the first effort.\nOn subsequent efforts work to capture as many meters as in the first effort.\n\nIn the same interval pattern, 20on/10off X 8,\nSquat (air squat).\nSame interval pull-ups.\nSame interval push-ups.\nSame interval sit-ups.\n\nIf you transition from one exercise to the next in ten seconds, this is a\ntwenty-minute workout. For all but the best athletes this will be all but impossible.\n\nTransition from one exercise to the next as quickly as you can. One-minute maximum\ntransition break! No ranking will be considered for total time that exceeds twenty-four minutes.\n\nRanking is based on least number of meters in each of eight rowing intervals, and least\nreps in each of eight intervals for each of the other four exercises.\n\nSubmission includes five numbers: least number of meters in rowing, least number of squats,\nleast number of pull-ups, least number of push-ups, and least number of sit-ups.\n\n\"One shouldn't be afraid to lose; this is sport. One day you win; another day you lose.\nOf course, everyone wants to be the best. This is normal. This is what sport is about.\nThis is why I love it.\"\nOlympic Gold Medallist Oksana Baiul\n\nThe 20 seconds on / 10 seconds off interval repeated 8 times is the interval first\nresearched by Dr. Izumi Tabata. The CrossFit crew was early pioneers of this interval\nand was first to apply it to the squat. Today we are going to use this interval with five\nseparate exercises. We will row, squat, pull-up, push-up, and sit-up. This represents\nthe range of functional movements (met. con, hip extension, pulling, pushing, and trunk/hip flexion).\nFirst review the Tabata interval:\nhttp://www.cbass.com/searchof.htm "
  },
  {
    "date": "2001-03-05",
    "text": "Today we are going to run and deadlift.\nThis was reported to be a pernicious combination last week,\nso here it is again! (Just for you, Garth)\n\nRun 200 meters, then immediately\nDeadlift 10 RM load (a load you can lift ten times but not eleven) 10X\nRest as needed\n\nRun 400 meters, then immediately\nDeadlift 5 RM load 5X\nRest as needed\n\nRun 600 meters, then immediately\nDeadlift 3 RM load 3X\nRest as needed\n\nRun 800 meters, then immediately\nDeadlift 1RM load 1X\nDone\nThese are max efforts at each lift. The runs are all-out, no whimping out!\nThe entire workout must be completed within an hour. No exceptions.\n\n\"You have to go into the jungle, find the lion, and spit in his face...then shoot him.\nYou guys are not good enough to win on talent alone...you have to want it.\"\nHerbie Brooks- coach of the 1980 U.S. Olympic hockey team\n\nHOW NOT TO JUMP!\nHere is a computer animation that simulates a vertical leap at three heights.\nThough the simulation MAY accurately represent typical mechanics of an\nuntrained athlete, it is flawed from the perspective of optimal performance.\nAll of this is amusing because the animators are proud of their incorporation\nof biomechanical analysis in their work. The biomechanical errors are not\nglaring but very real and fairly obvious. Can you report the problem?\n(Hint the problem is worse on landing than taking off.)\nhttp://www.cc.gatech.edu/gvu/animation/Areas/humanMotion/transitions/landing.qt"
  },
  {
    "date": "2001-03-06",
    "text": "200 sit-ups no matter how long it takes. Make them nice!\nStretch thoroughly. Used as a rest to slow down pace and come in to the next phase relatively fresh.\nDo 50 dips, with or without assistance. This is a 50RM set, i.e., ideally, 51 should be impossible.\nImmediately, run for ten minutes on a “windsprint” bike or a stairclimber at max level.\nRest as needed.\nDo 35 dips, with or without assistance. This is a 35RM set, i.e., ideally, 36 should be impossible.\nImmediately, run for five minutes on a “windsprint” bike or a stairclimber at max level.\nRest as needed.\nDo 20 dips, with or without assistance. This is a 20RM set, i.e., ideally, 20 should be impossible.\nImmediately, run for five minutes on a “windsprint” bike or a stairclimber at max level.\n200 sit-ups no matter how long it takes. Again, make them nice!\n\nNote: Do as many of the dips as you can without assistance on failure jump to Gravitron\n(or like) and complete set with minimal assistance. We are exhausting the pushing function\npartially with an eye to making the arm supporting contribution on the bike or stairlcimber\nvery tough\n\n\"There will come a point in the race, when you alone will need to decide. You will need to\nmake a choice. Do you really want it? You will need to decide.\"\nRolf Arands\n\nWe're going back to Dr. Seiler's site today for a look at lactate threshold. For you techies\nand coaches this is essential stuff. You may recall that lactate threshold is the second\nwave of endurance adaptation. (The first being VO2 max.) At CrossFit we are only\ninterested in the first two waves of adaptive response. The third comes at great cost to\nyour overall physical capacity. http://home.hia.no/~stephens/lacthres.htm"
  },
  {
    "date": "2001-03-07",
    "text": "Row 5k\n\n\"The heights which great men reached and kept, were not attained by sudden flight,\nthey, whilst their companions slept, were toiling upwards in the night.\nHenry Wadsworth Longfellow\n\nI know I've discussed high intensity training protocols versus periodized protocols with\nsome of you. Here is a coach, Jim Kielbaso, defending the high intensity training (HIT)\nprotocol with remarkable candor. In the world of strength and conditioning, the coach\nis still the authority, not the scientist.\nhttp://www.cyberpump.com/hitstuff/callit.html"
  },
  {
    "date": "2001-03-08",
    "text": "Today we are employing a drill the CrossFit crew calls the “wall-ball.” The wall-ball drill is\na deep front squat followed through with a push-press and overhead throw. The ball, a\n20 lb Dynamax medicine ball should make contact with the wall at about two feet over your\nreach and rebound to your hands where you immediately bring the ball back to your chest\nand squat to absorb the impact. The movements up and down are mechanically identical.\nStand about 18 inches away from the wall. The idea is to be in constant motion either on\nthe way up or catching and lowering. The major faults here are either to not squat to\nparallel and to let the ball contact with a thud rather than gently absorbing the impact with\nthe arms and legs.\n\nRun 800 meters.\nStretch for ten minutes.\n\nWall-ball for 50 throws within 2 minutes.\nImmediately do as many pull-ups as possible in five minutes.\nRest 5 minutes.\nWall-ball for 50 throws within 2 minutes.\nImmediately do as many pull-ups as possible in five minutes.\nRest 5 minutes.\nWall-ball for 50 throws within 2 minutes.\nImmediately do as many pull-ups as possible in five minutes.\nRest 5 minutes.\nRun 800 meters.\n\nStretch for ten minutes.\n\n\"Don't worry about upgrading your equipment. Upgrade your body.\"\n-Anonymous cyclist\n\nThere are adaptations to endurance training that are inconsistent with the needs\nand aims of most athletes. Endurance work is vital, yet must be limited if you want\noptimal fitness and health. Here is Dr. Seiler articulating the third wave of adaptation\nto endurance training. The adaptation he reviews in this article is essential to elite\nendurance performance. Can you explain precisely what it is about this adaptation\nthat seriously curtails elite high intensity performance?\nhttp://home.hia.no/~stephens/effiperf.htm"
  },
  {
    "date": "2001-03-09",
    "text": "Jump rope, double under for two minutes.\n(Double under is where the rope passes under the legs twice for each jump)\nLunge forty steps, twenty each leg, alternating right and left.\nBench-press body weight for max reps.\nLunge twenty steps, ten each leg, alternating right and left leg with dumbbells totaling 1/3 your weight.\nBench-press body weight for max reps.\nLunge 10 steps, five each leg, alternating right and left leg with dumbbells totaling ½ your weight.\nBench-press body weight for max reps.\nJump rope, double under for two minutes.\n\nThese are walking lunges, not the ineffective ones!\nSubmit time and bench press reps for ranking.\n\n\"Perfection is not attainable, but if we chase perfection we can catch excellence.\"\nVince Lombardi\n\nPaul Chek runs a program in San Diego that shares many of the CrossFit precepts.\nHere Paul is taking a shot at bodybuilders.\nhttp://www.paulchekseminars.com/articles.cfm?select=4"
  },
  {
    "date": "2001-03-10",
    "text": "Today we are swimming. This is a breathing exercise designed to improve\nanaerobic performance. We’re taking a bit of a break. Get ready for Monday!!\nSwim the entire length of an Olympic Pool underwater.\nWhen able, return surfacing once at about the middle of the pool.\nAgain, as soon as able cross. This time surfacing only twice, once at\nabout 1/3 across and again at 2/3 across.\nRepeat this pattern 4 times for a total of 5 times or fifteen lengths.\nRecord your total time to complete the exercise.\nDone right, this has much of the feel of drowning. Good luck!\n\nRankings based on total time to completion. Rest after each pass only as long\nas needed to complete the next pass. If you should have to surface more than\nthe pass requires, rest andrepeat the effort.\n\n\"Part of the beauty and much of the moral seriousness of sport derives from the\nsevere justice of strenuous play in a circumscribed universe of rules that protect\nthe integrity of competition. Records are worth recording, and worth striving to\nsurpass, because they serve as benchmarks of excellence achieved under the\npressure of competition.”\nGeorge F. Will\n\nWe recently examined the effects of aging on skeletal muscle. Here’s Jim Martin,\nan exercise scientist from University of Texas, Austin on the effects of aging on\nperformance, specifically power.\nhttp://home.hia.no/~stephens/maxpower.htm"
  },
  {
    "date": "2001-03-11",
    "text": "Rest Day\n\n\"If you believe in yourself, have dedication and pride and never quit, you'll be a winner.\nThe price of victory is high, but so are the rewards.” Paul \"Bear\" Bryant\n(Late, great coach of the Alabama Crimson Tide football team)"
  },
  {
    "date": "2001-03-12",
    "text": "Here we go again!!\nWe're returning to the \"CrossFit Challenge\":\nApply the \"Tabata Interval\"\n(20 secs of work followed by 10 secs of rest repeated 8 times) to:\n\nRowing\nSquatting\nPull-ups\nPush-ups\nSit-ups\n\nFor the Rowing record the number of meters you complete in each interval.\nFor the other exercises record the number of reps you complete in each interval.\n\nYou get a minute break between each exercise.\nThe lowest numbers from each exercise are added for a total score.\nThis is an extremely challenging workout. It takes exactly 24 minutes to completion.\nYour final score is an excellent measure of your total fitness\n\n\"The doctor of the future will give no medicine, but will interest his patients in the care\nof human frame, and in the cause and prevention of disease.\"\nT. A. Edison\n\nThe evolutionary argument for the Paleolithic Diet is powerful, sound, and compelling.\nWe will regularly return to this thread. It is well worth the time to bookmark this link and\nexplore its reaches until you are intimate with the details of this perspective. http://www.beyondveg.com/cat/paleodiet/index.shtml "
  },
  {
    "date": "2001-03-13",
    "text": "Today we're on bikes. Find a climb, close to home, of about 1,000 feet.\nTackle this thing with every once of effort you can muster. This is a 100% effort.\nSubmit/save the time for posterity\n\nThe psychological and metabolic benefits of high intensity hill climbing, i.e., competitively\nand for time, are enormous. If you don't like it, good. If you think it's fun it's doing you no good.\nBe tough, be aggressive.\n\n\"All men are created equal, some are just faster than others\"\nDarren Franklin, amateur mountain biker\n\nHere are some thoughts on bicycle hill climbing.\nhttp://www.chainreactionbicycles.com/hills.htm\nAnd a little technique.\nhttp://www.bicyclesource.com/you/road/road-climbing.shtml"
  },
  {
    "date": "2001-03-14",
    "text": "Stretch: back, hips, legs, chest, shoulders.\n\nTrunk flexion: sit-ups.\nTrunk extension: back extension.\nHip flexion: knee ups.\nHip extension: air squats.\nPush: dips.\nPull: pull-ups.\nWeightlifting: deadlift\nRow: 2K meters\n\nStretch: back, hips, legs, chest, shoulders.\n\nSee how tough you can make this workout. This is a high intensity training session.\nWe're just doing one set of each exercise make it a killer! Each set should be a max effort.\nNo resting during set. Rest as needed between exercises.\n\nReport your efforts for feedback. Include times in your workout, but don't include stretch time in total.\n\n\"Even the strongest have their moments of fatigue.\"\nFriedrich Nietzsche\n\nHere is a cheater's version (yet still of extraordinary value) of the one legged squat.\nThe one legged squat has much of the quality of a weightlifting movement but still a calisthenic. http://weww.totalcoaching.com/strength/onelegsquat.html"
  },
  {
    "date": "2001-03-15",
    "text": "Start with a calisthenic, whole body, single set per exercise mini-routine.\nWe will explore dozens of these \"mini workout warm-ups\". They all contain\nelements of hip/trunk flexion & extension, pushing and pulling.\n\nStretch (hips, legs, back, chest, and shoulders)\n\nSit-ups\nBack extensions\nSquats\nRope climb or pull-ups\nDips or push-ups\nClean and Jerk 15,12, and 9 reps (If you need help with this movement contact us.\nWe offer regular free seminars in the Olympic lifts)\n\nFinish with the same effort coming in.\nSit-ups\nBack extensions\nSquats\nRope Climb or pull-ups\nDips or Push-ups\n\nStretch\n\nNo metabolic conditioning today. That suggests something about tomorrow to those\nof you who are paying attention.\n\n\"Nobody ever got fit, or even close, through a combination of long slow aerobics\nand bodybuilding routines.\"\n-Greg Glassman\n\nThe USDA places grains at the base of its utterly ridiculous food pyramid. Here is\nsome sanity brought to that issue by Dr. Cordain.\nhttp://www.beyondveg.com/cordain-l/grains-leg/grains-legumes-1a.shtml"
  },
  {
    "date": "2001-03-16",
    "text": "Row a 2K for a personal best.\n\nWe will continue today on our recurrent theme of core-focus.\n\n1) Hanging from the pull-up bar SLOWLY lean back and lift your feet towards your\nhands until your tows gently touch the bar. Repeat for a total of twenty times.\n2) Arch rock for one minute. If you've forgotten what the arch rock is go to: http://www.audiblefaith.com/artists/rharrell/gympag/condstr.html\n(You are supposed to be practicing for the moves on this page regularly anyway!!\n3) Fifty sit-ups with substantial support (towel or abmat, etc.) under the lumbar spine.\nKnees up and apart, feet together.\n4) Thirty back extensions.\n5) Hollow Rocks for sixty seconds. Again if you've forgotten: http://www.audiblefaith.com/artists/rharrell/gympag/condstr.html\n6) 20 Stiff legged deadlifts. These are performed with an arched back! From the stand,\nbow down letting the chest lag behind as far as possible. Do not surrender the arch in\nyour lower back. Done right you won't get anywhere near the floor with the barbell. If\nyour mechanics are correct you will feel an extraordinary tightness in the hamstrings.\n7) Hold an L for sixty seconds. Repeat two times for a total of three efforts.\n8) Twenty five times perform a \"hug-a-twinky\". If you don't know the movement here it is: http://www.audiblefaith.com/artists/rharrell/gympag/condstr.html\n\nSome of you may be tempted to slough off the moves that you can't perform. You need to\nunderstand that what you can't do here clearly defines your deficiencies as an athlete.\nAny reasonably conditioned athlete can do all of these without much difficulty. If you find\na chink in your armor, work daily on correcting it.\n\n\"Man is not cut out for defeat. Man can be destroyed but not defeated.\"\nE. Hemingway\n\nWe included this link from this same thread about two weeks ago. Not enough of you paid\nclose enough attention, so we are including it again. There is a gold mine of information\nhere about proper training of your abdominal muscles. This is must reading!\nhttp://www.abmat.com/intro.htm"
  },
  {
    "date": "2001-03-17",
    "text": "Today's workout is a \"gimme.\" We are doing five sets of bench press.\nWe are giving the \"power-zone\" (mid-section) a rest. Know why?\n\nPerform your bench press at 5-4-3-2-1 reps. Increase weight at each set.\nTake long break between sets. Go for max weight at each lift.\n\nStretch.\n\n\"Excess, upon occasion can be exhilarating, because it prevents moderation from\nacquiring the deadening effect of a habit.\"\nSomerset Maugham\n\nThe CrossFit Program harvests a multitude of elements from the sport of gymnastics.\nHere is a page of floor exercise skills and drills. Moves are graded A-E, from easiest\nto hardest. See how many of the A moves you can to. Study as many of the moves\nyou can. The first step to kinematics mastery begins in the imagination. Advanced\nbody control firsts manifests as extraordinary will.\nhttp://www.drillsandskills.com/skills/Floor/Z"
  },
  {
    "date": "2001-03-18",
    "text": "Today: Find your way to a track with a place for pull-ups.\nOften, there will be parallel bars as well as a pull-up bar.\nRun 400 meters (once around for those new to the track)\nDo 50 pull-ups in as many sets as required\n(if you don't have 10 pull-ups, do 200 jumping pull-ups)\nRun 400 meters\nDo 50 dips or 75 push-ups in as many sets as required\nRun 400 meters\nDo 75 air squats\nRun 400 meters\n\nRanking based on total time for workout\n\n\"Far better it is to dare mighty things, to win glorious triumphs, even though checkered\nby failure . . . than to rank with those poor spirits who neither enjoy much nor suffer\nmuch, because they live in a gray twilight that knows not victory nor defeat.\"\nTheodore Roosevelt\n\nThe message regarding sound nutrition must filter through a ceaseless torrent of\nmisinformation from the popular media. Here is more on the paleodiet:\nhttp://www.paleodiet.com/lindeberg/"
  },
  {
    "date": "2001-03-19",
    "text": "Back Squat for five sets each at ten reps:\n1st Super-slow, 20 seconds round trip\n2nd Bottom-to-bottom (rest at bottom, no stop at top)\n3rd Ten second pause at bottom of each rep\n4th Eyes closed (better use spotter or you'll die)\n5th Ease down, EXPLODE-UP!!!\nSwim a mile. This is about 30 lengths of a 50-meter pool\n\n\"Explosive hip extension is necessary, and damned near sufficient, for elite athleticism.\"\nCoach Glassman\n\nMidline stability, control of the major body axis, is a CrossFit constant.\nHere is the concept applied to track sprinting. http://www.pnc.com.au/~stevebn/sprint.htm"
  },
  {
    "date": "2001-03-20",
    "text": "Today we start and end with our calisthenic warm-up and cool down and throw a\nlittle rowing and power cleans in the middle. There's no break between the rowing\nand the power cleans. The warm-up and cool down are max or near max rep sets\nwith lots of rest between efforts. This is a tough one.\n\nAb bench\nBack extensios\nAir Squat\nPull-up\nDip\nRow 500 meters\nPower Clean 21 reps\nRest 5 minutes\nRow 500 meters\nPower Clean 15 reps\nRest 5 minutes\nRow 500 meters\nPower Clean 9 reps\nRest 5 minutes\nAb bench\nBack extension\nAir Squat\nPull-up\nDip\n\n\"I don't know what's wrong with my damned dog; he's dying. He can't keep his food down;\nhe's salivating and trembling, and I've got him on the best vegetarian diet that money can buy!\"\n-Bob\n\nSpeaking of vegetarian diets, this is interesting:\nhttp://www.beyondveg.com/cordain-l/metab-carn/metabolic-carnivory-1a.shtml"
  },
  {
    "date": "2001-03-21",
    "text": "Five sets of the triple,\nSit-up\nBack extension\nBench-press 5-10RM\n\nMove methodically, deliberately, with precise SLOW movement.\nDon't hurry; minimize the cardiovascular quality. This is strength training only!\nMake each effort a serious challenge.\n\n\"When a person trains once, nothing happens. When a person forces himself to\ndo a thing a hundred or a thousand times, then he certainly has developed in more\nways than physical. Is it raining? That doesn't matter. Am I tired? That doesn't matter,\neither. Then willpower will be no problem.\" Emil Zatopek\n\nThe nutritional value of fruit is a regular topic when discussing diets. This is especially\nthe case with our Jiu-jitsu friends following the famed Gracie diet. Fruit lovers beware!\nhttp://www.beyondveg.com/cat/fruit-dreams/index.shtml"
  },
  {
    "date": "2001-03-22",
    "text": "Jump Rope 300 jumps\nSit-up 30\nBack extension 20\nWalking Lunge 30 steps\nPush-ups 30\nPull-ups 15\n\nBike 1.5 miles\nAb bench 25% BW X 25\nStiff Legged Deadlift 50% BW X 21\nDeadlift 75% BW X 15\nBench-press 75% BW X 12\nUpright Row 50% BW X 10\n\nRow 1000 meters\nHollow Rock 1 min\nArch Rock 1 min\nBack Squat 75% BW X 15\nPush-press 50% BW X 12\nPower Clean 50% BW X 10\n\nCalculate loads (BW = body weight) before beginning.\nTime entire workout. Shortest time \"takes it.\"\n\n\"A True Warrior Never Fights Without a Purpose That is Greater Than Oneself.\"T. Harv Eker\n\nHere's a great athlete celebrating one of the greatest coaches of all time while sharing\nsome valuable insights into coaching.\nhttp://www.usa-gymnastics.org/publications/technique/2000/8/valueofcoach.html"
  },
  {
    "date": "2001-03-23",
    "text": "Today is trunk work and a run.\n\n30 sit-ups and 21 back extensions\nRun 1 mile for time\n\nNo rest between sets for the following:\n50 sit-ups\n21 back extensions\nHang from bar and slowly raise legs, curl and touch toes to bar 25 times.\nArch rock 1 minute\n25 crunches on glute-ham back extension apparatus (upside down on back extension app.)\nStiff-legged deadlift 50 % BW for 25 reps\n\nStretch\n\n\"Wisdom is better than strength. And a wise man is better than a strong man.\"\nBook of Wisdom 6:1\n\nOur crew spends a good deal of time on the Concept II Rowing Ergometer.\nHere is Dr. Seiler examining gender and weight differences, and water performance\nas related to the Concept II performance.\nhttp://home.hia.no/~stephens/eliteerg.htm"
  },
  {
    "date": "2001-03-24",
    "text": "You guessed it, today we are determining our total for the three Powerlifting lifts,\nthe deadlift, bench-press, and the squat.\n\nTake your time. Warm-up with sets of three to five reps. Rest. Increase the weight,\ndrop the reps, and lift again. Repeat this process until you've established a max\nweight for each lift. Total the lifts and submit for ranking. The total is comprised of\nyour max lift at one rep for each exercise\n\n\"We keep going back, stronger, not weaker, because we will not allow rejection to\nbeat us down. It will only strengthen our resolve. To be successful there is no\nother way.\"\n~ Earl G. Graves ~\n\nOur weight training culminates in the sport of Weightlifting; this is the Olympic sport\nthat includes the \"Clean and Jerk\" and the \"Snatch.\" The squat, bench-press, and\ndeadlift are used to support and develop the Olympic Lifts and themselves constitute\nthe sport of Powerlifting. CrossFit employs the training techniques and lifts therefore\nof both Olympic Weightlifting and Powerlifting as primary weight training concerns.\nHere is a site of valuable Powerlifting and Weightlifting sites:\nhttp://www.goheavy.com/links/"
  },
  {
    "date": "2001-03-25",
    "text": "Rest Day\n\nI am responsible. Although I may not be able to prevent the worst from happening,\nI am responsible for my attitude toward the inevitable misfortunes that darken life.\nBad things do happen; how I respond to them defines my character and the quality\nof my life. I can choose to sit in perpetual sadness, immobilized by the gravity of my\nloss, or I can choose to rise from the pain and treasure the most precious gift I have\n- life itself.\n~ Walter Anderson ~\n(American Trainer, Author)"
  },
  {
    "date": "2001-03-26",
    "text": "Ab-bench (or other sit-up that ranges from trunk extension through to flexion) 30 reps at max weight\nBack extension 25 reps\nAir Squat 50 reps\n\nFor the next phase we are doing pull-ups and dips or muscle-ups if you've got one!\n\nSix sets of pull-ups (max effort, record the total, take as much time as needed between sets)\nAnd,\nSix sets of dips (max effort, record the total, take as much time as needed between sets.\nOR, if you have a muscle-up,\nTen muscle-ups (max effort, take as much time as needed, record the time to complete all ten)\n\nOne rope climb with no legs or five with legs.\nTwenty handstand push-ups by any means. Have spotter pull you up by ankles if needed.\n\nPractice lowering from handstand to planche (body parallel to floor, arms locked) Have spotter\nsupport your ankles and lower you to parallel. Hold at parallel, with spotter minimally helping,\nfor five full seconds.\n\nRepeat for ten attempts. Do on padded mat, crash pad, or other padded surface!!\nAb-bench (or other sit-up that ranges from trunk extension through to flexion) 30 reps at max weight\nBack extension 25 reps\nAir Squat 50 reps\n\nThis is a really tough day. Don't hold back. Tomorrow is met-con only, so you will be able to rest\nyour arms, back, and shoulders. You are getting a small taste of the demands of a gymnast's workout."
  },
  {
    "date": "2001-03-27",
    "text": "Today is metabolic conditioning:\n\nWarm-up through stretching then,\n\nRow 500 meters\nRest 10 minutes\nRow 1000 meters\nRest 10 minutes\nRow 2000 meters\nRest 10 minutes\nHang from pull-up bar and slowly touch toes to bar 20 times\nBack extension 20 reps\nRest 1 minute\n50 sit-ups, use ab mat\nBack extension 20 reps\nRest 1 minute\n25 Pike-ups (laying face up flex rapidly at the hip only touching the toes\nbefore unfolding, minimize trunk flexion)\n30 slow reverse back extensions (lie across something dangling legs\nand hips freely then slowly without throwing bring legs and hips up to\nparallel, hold and relax)\n\nWhen you blame others you give up your power to change.\n~ Author Unknown ~\n\nHere is a good article on hamstring anatomy and physiology that I recommend you all read.\nMr. Poliquin is a first tier trainer. The anatomy here is indispensable. The physiology is good.\nThe exercise prescription is OK.\nhttp://www.charlespoliquin.net/charles_poliquin/articles/hamstring1.htm"
  },
  {
    "date": "2001-03-28",
    "text": "Each of these exercises is one set at five reps. Take any rest needed between exercises.\nDeadlift\nBench-press\nUpright row\nBack Squat\nPush-press\nPower Clean (from ground)\nDumbbell \"Thruster\" (front squat/push-press)\nClean and Jerk\nSnatch\n\nAdd your total lifted for all nine exercises and divide by your body weight.\nHighest ratio leads ranking.\n\nOne of the rules of caution is not to be too cautious.\n~ Bahya ibn Paquda ~\n\nPicking up The Anatomy Coloring Book and following its fun prescription for learning\nanatomy through coloring in the anatomical charts provides a major advance to your\nunderstanding of your body and how it functions. If you think you are too sophisticated\nfor this approach consider that the book has been used by professional schools of\nmedicine, dentistry, and pharmacology for 25 years. Get the book and fine tip felt\nmarkers in no fewer than twenty colors, and color a couple of plates a week. Within a\nyear you'll have seriously advanced your understanding of the human body. Read the\ninstructions; that's essential. Here's the link to Amazon.com for the book: http://www.amazon.com/exec/obidos/ASIN/0064550168/o/qid=985663341/sr=8-1/ref=aps_sr_b_1_1/002-8298663-4861620"
  },
  {
    "date": "2001-03-29",
    "text": "On Monday we worked gymnastics/calisthenic movements, on Tuesday we worked\nmetabolic conditioning with a short, middle, and long distance effort, Wednesday we\nworked through some of the classics of weightlifting and weight training. Today we\nare taking a day of active rest. If you’ve performed to expectation you’ll welcome the\nbreak. If you know our methods, you'll make an intelligent inference about tomorrow (hint).\n\nThe idea here is to engage in some sport or activity at intensity above recreational while\nbeing below our regular training intensity. Don't count your primary sport! This is a\ncross-training opportunity. Step outside your normal bounds. Below are some suggestions.\n\nBicycle Hill Climb\nHoops! (Basketball)\nSwimming\nMountain Hike\nRollerblade\nSurf Paddle\nHandball or racquetball\nTennis\n\nLet us not be content to wait and see what will happen, but give us the determination to make the right things happen.\n~ Peter Marshall ~\n(1902-1949, American Presbyterian Clergyman)\n\nThe bench press is a classic exercise. Though overvalued in popular lore it is still without a\ndoubt indispensable to your weight training program. Here is an article on bench press technique\nfrom a champion and coach of champions, Dave Tate, of Westside Barbell Club, an epicenter of\nPowerlifting achievement.\nhttp://www.testosterone.net/html/body_115b600.html"
  },
  {
    "date": "2001-03-30",
    "text": "Today is a hybrid effort from several training modalities and tough!!\nAfter a warm-up:\nMove through the following with a 60 second break between exercises.\nRow 500 meters for a record time.\nSquat 20 RM weight 20 reps (20 RM is a weight you can squat 20 reps but not 21.)\nPull-up for PR (shoot for personal best)\nDeadlift 10 RM weight 10 reps\nDips for PR (shoot for personal best)\nRest 10 minutes\nMove through the following with a 2-minute break between exercises.\nRow 500 meters match first effort\nSquat same weight for twenty reps\nPull-ups for same count as first set\nDeadlift same weight for 10 reps\nDips for same count as first set\nRest 10 minutes\nMove through the following with a 3-minute break between exercises.\nRow 500 meters match first effort\nSquat same weight for twenty reps\nPull-ups for same count as first set\nDeadlift same weight for 10 reps\nDips for same count as first set\n\nThe idea today is to strive to match the performance of the first pass on the second and third.\n\n\"Egotism is the anesthetic that dulls the pain of stupidity.\"\n- Frank Leahy, former University of Notre Dame football coach\n\nYesterday we had David Tate coaching bench press technique. Today we've got\nMr. Tate coaching the squat. The squat is absolutely essential to your athletic\ndevelopment. Tate has a 900-pound squat and has coached hundreds if not\nthousands of others to enormous lifts. Our emphasis is broader than the powerlifter's\nso there are certain elements of the squatting approach where we differ, namely in\nthe use of a belt and the use of the belly (secret #7). We want you to gloss over that\nadvice. If you'd like an explanation of our perspective on lifting belts bring it up on the\nCrossFit message board.\nhttp://www.testosterone.net/html/body_149squat.html"
  },
  {
    "date": "2001-03-31",
    "text": "Warm-up with easy mile run and stretch\nClean and Jerk 15 RM load 15 reps\nOne set of sit-ups and one set of back extensions both at 21 reps\nClean and Jerk 15 RM load 12 reps\nOne set of sit-ups and one set of back extensions both at 18 reps\nClean and Jerk 15 RM load 9 reps\nOne set of sit-ups and one set of back extensions both at 15 reps\n\n\"I don't know what happened to the guy, I was just holding the watch!\"\nGarth Taylor, Brazilian Jiu Jitsu World Champion on seeing running back\nMatt Mast \"fold\" during the CrossFit Challenge.\n\nHere's another view of the Clean and Jerk from USA Weightlifting.http://www.usaweightlifting.org/lifts/cleanjerk.htm "
  },
  {
    "date": "2001-04-01",
    "text": "Today we are going to run twenty miles.\n\nIf this seem to far you are right.\nYou are also the victim of our little April Fool's Day Joke.\nActually, today is a rest day. Stretch, play, and relax.\nMake it active rest though. Do something active and fun\n\nThere are some things you learn best in calm, and some in storm.\n~ Willa Cather ~\n(1876-1947, American Author)\n\nHere's USA Weightlifting describing how to perform the Snatch:\nhttp://www.usaweightlifting.org/lifts/snatch.htm\nThe picture sequence isn't real good but they're the experts, right?\nGive us feedback on what's wrong with the photo sequence"
  },
  {
    "date": "2001-04-02",
    "text": "Row 1K\nPull-up (max set)\nDumbell Thruster* (21 reps)\nDumbell Thruster (21 reps)\nPull-up (max set)\nRow 1K\n\nThe idea here is to match the numbers of the second half with the number of the first half.\nGo through this slowly! Take as much time as you need.\nWork for your best effort in each exercise.\n*Dumbell Thruster is from a full squat to a push press overhead"
  },
  {
    "date": "2001-04-03",
    "text": "1 mile run\n50 sit-ups and 25 back extensions\nDeadlift/high-pull 18,15,12, and 9 reps\n50 sit-ups and 25 back extensions\n1 mile run\n\nOur Deadlift high-pull is a slow deadlift and slow deliberate upright row\nto under the chin with brief hold at top. Very slow, very deliberate. Tough.\n\nPower through the trunk work and run. Move slowly and deliberately through the deadlift/high-pull.\n\nSerious sport has nothing to do with fair play. It is bound up with hatred, jealousy,\nboastfulness, disregard of all rules and sadistic pleasure in witnessing violence.\nIn other words, it is war minus the shooting\n- George Orwell\n\nSports is like a war without the killing.\n- Ted Turner\n\nThis is a GOOD one: http://www.cbass.com/Intensity.htm."
  },
  {
    "date": "2001-04-04",
    "text": "\"Tabata Interval\" Squat\n(Squat for 20 seconds, rest for ten, repeat for total of 8 efforts in 4 minutes)\nRest 4 minutes\n20 Pull-ups (assisted if needed), followed immediately by 20 reps Bench press\nRest 3 minutes\n15 Pull-ups, followed immediately by 15 reps Bench press\nRest 2 minutes\n10 Pull-ups, followed immediately by 10 reps Bench press\nRest 1 minute\n\n\"Tabata Interval\" Squat\n(Squat for 20 seconds, rest for ten, repeat for total of 8 efforts in 4 minutes)\n\nTake note of the weakest number of squats in each of the 16 intervals.\nUse the least amount of assistance possible to complete the pull-ups and use\nmax load on bench press.\n\nThis entire workout takes just over twenty minutes. Take note of the devastation.\nAsk yourself what it is that your friends are doing in the gym for hours at a time.\n\n\"I always turn to the sports page first. They record people's accomplishments;\nthe front page, nothing but man's failure.\"\n- Earl Warren, former Chief Justice, U.S. Supreme Court\n\nHere's more on the \"Tabata Interval.\" Applying it to the squat and other\nexercises is a CrossFit original.\nhttp://www.pponline.co.uk/encyc/0145.htm#\nThe argument posited here for adapting a variety of interval strategies jives\nperfectly with the CrossFit Model."
  },
  {
    "date": "2001-04-05",
    "text": "Most of you are a little beat up by now. Let's work a little triathlon CrossFit style, short and hard.\n\nBike 3 miles\nSwim 500 meters\nRun 1000 meters\n\nThe challenge will be to set up the transitions to minimize the transition time.\nShare with us your total time for all three legs and your transition strategy.\nWe’re leaving the order of events to your discretion!!\n\nIf the triathlon community competed at these distances or shorter, the triathlete\nwould be a much better athlete!\n\nAnd finally, for our athletes, today represents a day of active rest. Some rest, huh?\n\n\"The test and the use of man's education is that he finds pleasure in the exercise of his mind.\"\nJacques Barzun, Dean of Graduate School, Columbia University\n\nWe routinely get requests for basic information on exercise science. If you own only one\nreference on exercise it ought to be the National Strength and Conditioning Association's\nEssentials of Strength Training and Conditioning. The NSCA is a non-profit agency that\npublishes several peer-reviewed journals of exercise science. They have no peer in the\nfield of strength and conditioning research. You are supporting this site when you order\nyour copy of Essentials of Strength Training and Conditioning from this link:"
  },
  {
    "date": "2001-04-06",
    "text": "Row a record 2K.\nWhen able,\nHang Clean 50% of bodyweight (.5BW), 21 reps\nRest only as needed\nRow a 1K at 2K pace from first pass\nWhen able,\nHang Clean .5BW, 21 reps\nRested only as needed\nRow 500 meters at 2K pace from first pass\nWhen able,\nHang Clean .5BW, 21 reps\nWarm-up, of course, before beginning.\n\nEach pass is easier than the one before except for fatigue.\nKeep your faith and keep moving. Submit time for entire workout.\n\nIf you are up to the challenge, Hang Clean at 75% Body Weight\n\nTake rest; a field that has rested gives a bountiful crop.\nOvid, BC 43-18 AD, Roman Poet\n\nBob Anderson's Stretching has become an industry standard on the subject of stretching.\nNoted for it's utter simplicity, Stretching has just celebrated its 20th anniversary."
  },
  {
    "date": "2001-04-07",
    "text": "You've got 20 minutes to do as many pull-ups, squats (free-squat, or air squat),\npush-ups, and sit-ups and back extensions as possible. There's one rule; the total\nnumber of reps must include equal counts of each exercise. Work hard and fast.\n(I'd suggest you try reps of five of each and see if you can move continuously for the thirty minutes.)\n\nThe qualities and capacities that are important in running - such factors as will power,\nthe ability to apply effort during extreme fatigue and the acceptance of pain - have a\nradiating power that subtly influences one's life.\nJim Fixx\n\nToday's link is intended for coaches and trainers. It deals with a successful approach\nto minimizing liability: http://mason.gmu.edu/~jkozlows/p&r396.htm"
  },
  {
    "date": "2001-04-08",
    "text": "Let's put some energy in to the five CrossFit Challenges (No's 1-5)\n\nDon't let the enormity of the challenge deter your trying! Make a serious attempt at each\nchallenge and record the result. Save for late comparison. If you cannot do a muscle-up,\ntry anyway; the struggle is more important than the accomplishment.\n\nDaniel Kawika Bennett has achieved number 2, number 4 is Garth Taylor's,\nand number 5 belongs to Cameron Earle. No one has completed two challenges\n\n\"Suffering isn't ennobling; recovery is.\"\nChristiaan Barnard\n\nHere's some basic rowing physics. The physics of ergometers is included.\nThis is a good brain workout.\nhttp://www.atm.ox.ac.uk/rowing/physics.html"
  },
  {
    "date": "2001-04-09",
    "text": "50 dumbbell Thrusters with 25% of your bodyweight,\nimmediately,\nJump on 20ox 50 times within 2 minutes,\nimmediately,\nWalking lunge of 50 steps with dumbbells at 25% of your bodyweight,\nimmediately,\nRun 1 mile\n\n\"Courage is very important. Like a muscle, it is strengthened by use.\"\nRuth Gordon\n\nHere糠Dr. George Armelagos and Dr. Neil Smith of Emory University糠Department\nof Anthropology in an interview on the impact of the industrialization of food.\nhttp://www.emory.edu/COLLEGE/HYBRIDVIGOR/issue2/eons.htm"
  },
  {
    "date": "2001-04-10",
    "text": "Let's give the hips and legs a little break today! We've got three options today depending on your fitness ability. Pick one.\n\nWarm-up, including sit-ups and back extensions.\nDo 100 pull-ups and 100 dips on the Gravitron or other assisted pull-up/dip device.\nOR\nDo 50 pull-ups and 50 dips without assistance.\nOR\nDo 15 muscle-ups on the rings.\nFinish with sit-ups and back extensions.\n\nRegardless of which option you choose submit the number of sets and time it took\nto complete the assignment. In the case of assisted pull-ups/dips also submit the\namount of assistance.\n\n\"Courage is not simply one of the virtues, but the form of every virtue at the testing point.\"\nC.S. Lewis\n\nHere's Coach Dave Tate on torso training for the squat and deadlift. Seeing as how these\nmovements are extremely demanding on the torso we're assured something of interest in\nCoach Tate’s approach.\nhttp://www.musclemonthly.com/articles/010115-tate-westside-powerlifting.htm"
  },
  {
    "date": "2001-04-11",
    "text": "Today we are rowing some intervals that take us to the middle of the lactic acid pathway.\nSet the CII Rower for intervals a minute long with a minute's rest.\nWe are going to row ten of the intervals. This is a twenty-minute workout.\nOn the efforts, set the rower to projected meters and row the first interval at 95%\nOn the rest, row easy, maximizing your recovery.\nOn subsequent intervals attempt to repeat the distance covered on the first interval.\nSubmit your total distance for each of the ten intervals.\n\nIF YOU CAN'T ROW,\nOn a track run a lap, walk the next. Repeat until you've run ten and walked ten.\n\nTime only the runs, total and submit.\n\n\"You sit at the board and suddenly your heart leaps. Your hand trembles to pick up\nthe piece and move it. But what chess teaches you is that you must sit there calmly\nand think about whether it's really a good idea and whether there are other, better ideas.\"\n-Stanley Kubrick\n\nAs athletes we endeavor to show courage and determination. Endurance: Shackleton's\nIncredible Voyage may be the greatest story (true!) of perseverance ever told.\nWe encourage all out athletes to read it."
  },
  {
    "date": "2001-04-12",
    "text": "Tomorrow is a rest day.\n\nWarm-up with three sets of sit-ups and back extensions\nBench press 21 Reps max weight (21RM load 21 Reps)\nTwo minute all out sprint on stationary bike\nRest as needed before you...\nBench same weight as before, got 21?\nTwo minute all out sprint on stationary bike\nRest\n\nDone right, you're done\n\n\"Industry is a better horse to ride than genius.\"\nWalter Lippman\n\nCheck out the Skills and Drills site on gymnastics floor exercises\nhttp://www.drillsandskills.com/skills/Floor/\nThe point of the link is to encourage greater consideration of floor based exercises"
  },
  {
    "date": "2001-04-13",
    "text": "Rest Day\n\n\"He who cannot rest, cannot work; he who cannot let go, cannot hold on;\nhe who cannot find footing, cannot go forward.\"\nHarry Emerson Fosdick\n\nIronMInd sells strength-training equipment and publishes a journal, Milo. Everything\nDr. Strossen and IronMind has put together has been reputable, interesting, and valuable.\nRead through their site carefully and certainly order a catalog. The IronMind catalog is\narguably the best catalog in the fitness industry. At www.ironmind.com check out the\nlist of institutional clients to see what kind of reputation this small company has"
  },
  {
    "date": "2001-04-14",
    "text": "Clean and Jerk (Deadlift, hang-clean, push-press if you must)\n15,12, and 9 reps of 50-100% of your bodyweight.\n\nSnatch 15,12, and 9 reps.\n\nClimb a thousand to two thousand foot climb on your mountain bike or road bike.\n\nSent report as to your lift and climb. Who can plow through both fastest?\n\n\"Words of encouragement fan the spark of genius into the flame of achievement.\"\nWilfred A. Peterson\n\nCheck out the Encyclopedia of Weightlifting. This is the standard reference to the\nsport of weightlifting. Every coach and athlete who uses the Clean and Jerk and\nthe Snatch needs this book. The Weightlifting Encyclopedia"
  },
  {
    "date": "2001-04-15",
    "text": "Do three sets of chin-ups. Give yourself entirely to this task.\n100% Take any rest needed between sets.\nTotal three sets and submit.\n\nDo three sets of squats on a ten-inch box. Squat to seated, relax, and squat\nto stand with no sudden movements or postural shifts. The “landing” should\n be invisible to the observer. 50,35,20 reps with one minute break between sets.\n\nTime one hundred push-ups. Submit time.\n\nHow many sit-ups (good controlled ones, like the abmat sit-up)\ncan you do in five minutes? Submit count.\n\nCan you do thirty back extensions without \"throwing\" a single rep?\n\n\"Failure is only the opportunity to more intelligently begin again.\"\nHenry Ford\n\nHere are some thoughts on chin-ups and related exercises from cyberpump.com.\nThe chin-up is a much neglected exercise. http://www.cyberpump.com/trainhard/chin.html"
  },
  {
    "date": "2001-04-16",
    "text": "Warm-up with back extension, sit-up, pull-up, push-up, squat, and stretching.\nAbout ten to twelve minutes of near constant movement.\n\nOne minute of jump rope (double under if you're able) followed by one minute of rest.\nRepeat for a total of five times.\n\nPractice your handstand and handstand push-up.\nTry for three sets of handstand push-ups.\n\nOne set of back squats at twenty-one reps. Max weight.\n\nCool-down with back extension, sit-up, push-up, squat, and stretching.\nAbout ten to twelve minutes of near constant movement\n\n\"Nothing noble is done without risk.\"\nAndre Gide\n\nBob Whelan has been a rational voice in the strength-training world for decades.\nHere's his website; there's a reasonable mix of entertainment and information here. http://www.naturalstrength.com/"
  },
  {
    "date": "2001-04-17",
    "text": "Row three 500-meter efforts separated by not more than 5 minutes.\nAnyone sub 1:30 all three?\n\nOne set of push-ups. Please, only count the ones that lower the body\nrigidly as a unit to the floor and rise to full extension. T\nhese are RARE! Who's got 50?!\n\nTwo sets of deadlift. 5RM and 3RM loads. Warm-up sets don't count.\nAnyone twice body weight?\n\n\"Significantly improve your 400 meter run, two thousand meter row, squat,\ndead, bench, pull-up, and dip. Now you are a more formidable being.\"\n- Greg Glassman\n\nWe like gymnastics; we like strength training science. Here are both.\nhttp://www.usa-gymnastics.org/publications/technique/1996/8/strength-training.html"
  },
  {
    "date": "2001-04-18",
    "text": "Warm-up EZ sit-up, back ext., pull-up, push-up, air squat and stretch\n\n21 Rep push-press followed immediately by max set of pull-ups.\nRest as needed; you don't need more than three minutes\nRepeat for total of five combined sets.\n\nRun 1 mile.\n\n\"Self-pity is easily the most destructive of the nonpharmaceutical narcotics;\nit is addictive, gives momentary pleasure and separates the victim from reality.\"\n- John W. Gardner, President, Carnegie Foundation\n\nThe obstacle course has spectacular training potential yet is still seen primarily\nin military and police applications. CrossFitƳ C-cubed program was an attempt\nto radically increase the breadth of demand in an obstacle like manner. Here is\na good yet fairly typical obstacle course/program. Notice the quality of the\ndevelopment the women featured (yes, they run and teach their program) have\nacquired. This is a testament to functional exercises and mixed modality training.\nhttp://www.naturalmuscle.net/nm898/nmalter.htm"
  },
  {
    "date": "2001-04-19",
    "text": "Warm-up with five minutes of cardio, a single set each of sit-up,\nback extension, air squat, pull-up, push-up, and finally stretch.\n(This is the default CrossFit warm-up. Remember it, please.)\n\nComplete your warm-up with each of the following using comfortable loads.\nDeadlift, 1 set, 10 reps\nPower Clean, 1 set, 10 reps\nFront Squat, 1 set, 10 reps\nPush Press, 1 set, 10 reps\nGo heavy:\nClean and Jerk, 5 sets, 5,3,2,1,1 reps\nSnatch, 5 sets, 5,3,2,1,1 reps\n\n\"We must not cease from exploration. And at the end of all our exploring\nwill be to arrive where we began and to know the place for the first time.\"\n- TS Elliot\n\nFor those who have limited access to coaching of the Olympic Lifts, learning\nthe Clean & Jerk, and Snatch from photos and written instruction works. A\nhandful of world champions are self-taught; go for it. Here is some help; this\nis good stuff.\nhttp://www.ironmag.com/ct_olympic_lifts_part3_02.html"
  },
  {
    "date": "2001-04-20",
    "text": "Max set of pull-ups\nRun 800 meters\nMax set of pull-ups\nRun 400 meters\nMax set of pull-ups\nRun 200 meters\n\nReport entire time for workout and total for pull-ups.\n\n\"Sport must be amateur or it is not sport. Sports played professionally are entertainment.\"\nAvery Brundage, President, International Olympic Committee\n\nMany, new to our program, are asking about the power clean. Here's a quick and easy\ndescription of the power clean front squat complex.\nhttp://www.fitrex.com/fitness_info/exercise185.html"
  },
  {
    "date": "2001-04-21",
    "text": "Max set of pull-ups\nRun 800 meters\nMax set of pull-ups\nRun 400 meters\nMax set of pull-ups\nRun 200 meters\n\nReport entire time for workout and total for pull-ups.\n\n\"Sport must be amateur or it is not sport. Sports played professionally are entertainment.\"\nAvery Brundage, President, International Olympic Committee\n\nMany, new to our program, are asking about the power clean. Here's a quick and easy\ndescription of the power clean front squat complex.\nhttp://www.fitrex.com/fitness_info/exercise185.html"
  },
  {
    "date": "2001-04-22",
    "text": "Rest Day\n\nThe breaking wave / and the muscle as it contracts / obey the same law.\n / Delicate line / gathers the body's total strength / in a bold balance. /\nShall my soul meet / so severe a curve, journeying / on its way to form?\n- Dag Hammarskjold\n\nEleiko is the Rolls Royce of Weightlifting equipment. It's fun to review their site.\nParticularly interesting is the testing and engineering that goes in to the production\nof their bars. Many of our athletes and coaches dream of a facility filled with Eleiko\nequipment. http://www.eleikosport.se/index.html"
  },
  {
    "date": "2001-04-23",
    "text": "Rope Climb & Push-up: climb rope then perform 25 push-ups,\nrepeat for total of four times\nSquat three sets, 15, 5, and 3 reps\nRow 1000 meters\n\nI've had smarter people around me all my life, but I haven't run into one yet that\ncan outwork me. And if they can't outwork you, then smarts aren't going to do\nthem much good. That's just the way it is. And if you believe that and live by it,\nyou'd be surprised at how much fun you can have.\n- Woody Hayes\n\nCheck these freaks out! http://www.strongestman.com/magnus.html"
  },
  {
    "date": "2001-04-24",
    "text": "Run 800 meters two times\nSit-ups & Back Extension, superset three sets\nBench Press five sets all at ten reps, total weights\nJump-rope practice double under for ten minutes\n\nA lifetime contract for a coach means if you're ahead in the third quarter and\nmoving the ball, they can't fire you.\n-Lou Holtz\n\nSwimming technique has undergone a renaissance in the past decade.\nHere is a site featuring articles on swimming technique.\nhttp://www.swiminfo.com/technique/"
  },
  {
    "date": "2001-04-25",
    "text": "Push-ups & Pull-ups, do max set of push-ups then max set of pull-ups,\nrepeat for total of three times\nClean and Jerk, three sets, 15,12, and 9 reps\nRow 500 meters three times\n\nA sportswriter is entombed in a prolonged boyhood.\n-Jimmy Cannon\n\nTips, theory, routines, mechanics, you name it when it comes to bench press http://www.criticalbench.com/home.htm is your site."
  },
  {
    "date": "2001-04-26",
    "text": "Swim 400 meters three times\nHandstand & Pull-up, do as many pull-ups as the number of minutes\nit takes you to do twenty handstand push-ups\nDeadlift 5 sets all at three reps\nBike 20 sec's on 10 sec's off 8 times\n\nThe man who complains about the way the ball bounces is likely the one who dropped it.\n-Lou Holtz\n\nThrowing is an integral part of external object control and consequently power\ndevelopment. Here is the throwers site: http://www.longandstrong.com/"
  },
  {
    "date": "2001-04-27",
    "text": "Jump-rope, 1 minute double under/1 minute rest 5 times\nMuscle-up & Dip: do five muscle-ups with ten dips after each muscle-up\nSnatch two sets, 15 and 12 reps\nSwim 100 meters 4 times\n\nBoys, baseball is a game where you gotta have fun. You do that by winning.\n-Dave Bristol, Cincinnati Reds manager\n\nThis is a great, no frills site on strength training:\nhttp://www.strongassteel.net/"
  },
  {
    "date": "2001-04-28",
    "text": "Rope Climb & Handstand, six ascents and twenty minutes of handstand practice.\nSquat 4 sets, 10,8,6,4 reps\nRow 2000 meters\nJump rope, double under for two minutes.\n(Double under is where the rope passes under the legs twice for each jump)\nLunge forty steps, twenty each leg, alternating right and left.\nBench-press body weight for max reps.\nLunge twenty steps, ten each leg, alternating right and left leg with dumbbells totaling 1/3 your weight.\nBench-press body weight for max reps.\nLunge 10 steps, five each leg, alternating right and left leg with dumbbells totaling ½ your weight.\nBench-press body weight for max reps.\n\nIf you break 100, watch your golf. If you break 80, watch your business.\n-Joey Adams\n\nWe return again to Peak Performance. This time with a short piece on running technique.\nhttp://www.pponline.co.uk/encyc/0046.htm"
  },
  {
    "date": "2001-04-29",
    "text": "Rest Day\n\nPeople are about as happy as they make up their minds to be\"\nAbe Lincoln\n\nThis site has some interesting stuff though their perspective is poisoned\nby bodybuilding. We at CrossFit particularly like the garage/home gym angle,\nand we will be devoting a lot of our efforts in the future to helping all of you\nto build a world class strength and conditioning facility in your garage.\nhttp://www.monmouth.com/~rclodfelter/hghghp2.htmPeople"
  },
  {
    "date": "2001-04-30",
    "text": "For time:\nJump rope \"Double under\"; 90 seconds\n8 Clean and Jerks; 1/2 body weight\n6 Clean and Jerks; 3/4 body weight\n4 Clean and Jerks; body weight\n(no resting weight on ground)\nJump rope \"Double under\"; 90 seconds\n\n\"Nothing happens unless first a dream.\"\n- Carl Sandburg\n\nThis is a public forum for no frills weightlifting discussion.\nhttp://pub26.ezboard.com/boldschoolstrengthtraining70757"
  },
  {
    "date": "2001-05-01",
    "text": "Three rounds of:\n25 Sit-ups\n12 Back extension/glute-ham raises\nThen,\nThree rounds of:\nMax set of pull-ups\nMax set of push-ups\nWalking lunge twenty steps each right and left leg\n\n\"All of the top achievers I know are life-long learners.... Looking for\nnew skills, insights, and ideas. If they're not learning, they're not\ngrowing... not moving toward excellence.\"\n- Dennis Waitley\n\nHere is an excellent article on the use of the arms in running.\nThis is a critical technique element.\nhttp://dragon.acadiau.ca/~pbaudin/meganppr.html"
  },
  {
    "date": "2001-05-02",
    "text": "Deadlift 5-4-3-2-1 reps (total weight)\nRest 5 minutes\nBox jump (20\" box) 50 reps in 2 minutes (record time)\nRest 5 minutes\nRow 1000 meters (record time)\n\nSubmit deadlift total weight, 50 jump time, and 1K row time.\n\n\"In nature the distinction between strength training and cardiovascular\ntraining isn't always clear. It is the aim of effective athletic strength and\nconditioning prescription to deliberately blur that distinction.\"\nGreg Glassman\n\nHere is a cool training trick from the Westside Barbell Club: http://www.deepsquatter.com/strength/archives/ls01.htm"
  },
  {
    "date": "2001-05-03",
    "text": "Bike hard for ten minutes. (Record distance)\nRest three minutes\nOne set of pull-ups followed immediately by bench press at body weight.\nRest one minute\nSecond set of pull-ups followed immediately by bench press at body weight.\nRest one minute\nThird set of pull-ups followed immediately by bench press at body weight.\nRest two minutes\n\"Wall Ball\" drill for two minutes, attempt 50 throws\nRest only as long as it takes to complete 50 sit-ups, slow and controlled.\nBack extension/glute-ham raise 15 reps followed immediately by\n50 sit-ups\nWithout rest, repeat back ext./glute-ham raise and sit-ups.\n\nThis is a hard workout. Try to complete it in less than 40 minutes\n\n\"Health is the vital principle of bliss, and exercise, of health.\"\n- James Thomson (1700-1748)\n\nHere the legendary Louie Simmons of Westside Barbell Club offers some\nadvice on trunk training.\nhttp://www.deepsquatter.com/strength/archives/ls03.htm"
  },
  {
    "date": "2001-05-04",
    "text": "No WoD"
  },
  {
    "date": "2001-05-05",
    "text": "Back extension 15-15-15 slow and pretty. Snake or wave up.\nDumbbell \"thruster\" from 10\" box 20-15-10 max weight each set.\nNo \"rocking up\" or \"plunking down\"\n1000 meter row.\n\n(Thruster is a front-squat/push-press combo movement.)\n\n\"And thou wilt give thyself relief, if thou doest every act of thy life as if it were the last.\"\n- Marcus Aurelius\n\nLouie Simmons has had as much impact on strength training as any coach in the world.\nHe has mentored many of the best coaches in the U.S. It would be a foolish athlete that\nwould not be interested in his advice on squatting.\nHere it is! http://www.deepsquatter.com/strength/archives/ls32.htm"
  },
  {
    "date": "2001-05-06",
    "text": "Rest Day\n\nCrossFit would like to give a big congratulations to BJ Penn!\nBJ won his fight in the UFC last night in round one.\n\nWe are proud of you BJ"
  },
  {
    "date": "2001-05-07",
    "text": "Muscle snatch 15-12-9 reps\nwith same load and 1 minute between sets.\n\nFive supersets of back extension and sit-ups.\nMake each exercise slow and tough.\nAdd weight to back extension if ready. Go SLOWLY!\n\nMuscle snatch 15-12-9 reps\nwith same load and 1 minute between sets.\n\nThe muscle snatch is a snatch without the dive under the bar.\nThe idea is to deadlift and as you pass the knees, rapidly explode\nthe hip and follow through with an explosive pull straight through\nto locked out overhead. This snatch is a regular support exercise\nfrom the Olympic lifting repertoire. It places a heavy emphasis on\nthe upper body compared to the Snatch.\n\n\"The secret to a long life is to stay busy, get plenty of exercise and don't\ndrink too much. Then again, don't drink too little.\"\n- Hermann Smith-Johannson, 103-year-old cross-country skier\n\nYou want to learn as much about squatting from as you can.\n\nhttp://www.deepsquatter.com/strength/howIdothesquat.htm. Here is more\nsquatting advice from a good coach and this time we've got a video clip.\nWatch that bar bend!"
  },
  {
    "date": "2001-05-08",
    "text": "Time five muscle-ups and 50 box jumps on 20\" plyo box.\n\nStretch/rest 20 minutes.\n\nTime five muscle-ups and 50 box jumps on 20\" plyo box.\n\nWe're interested in both times and decay rate from first to second effort.\n\nIf you can't do muscle-ups, substitute fifteen pull-ups and twenty dips for each muscle-up.\nIf you can't do pull-ups and dips use assistance device (Cybex, Gravitron, etc.)\nIf you mix muscle-ups and pull-ups/dips report numbers of each with time.\n\n\"Suffering, once accepted, loses its edge, for the terror of it lessens,\nand what remains is generally far more manageable than we had imagined.\"\n- Lesley Hazelton\n\nJohn Cissek is a reliable source of information about the Olympic lifts.\nWe need to expose ourselves to as many descriptions and analysis as\nwe can in addition to regular practice in both the clean and jerk and the snatch."
  },
  {
    "date": "2001-05-09",
    "text": "Warm-up with about ten minutes of EASY rowing. Then...\n\nRow a 1K for time. Submit time.\n\nSquat (10\" box sqaut) 5-3-1 reps, submit total weight for all three sets\n\n\"If you think these workouts aren't tough enough, I've got news for you.\nYou are not a very good athlete yet.\"\n- Coach Glassman\n\nTake a look at the Concept II website and find how your 1,000 meter row\ntimes compares to an international pool of athletes. www.concept2.com."
  },
  {
    "date": "2001-05-10",
    "text": "Repeat this circuit three times with no rest. Push hard; make each set a worthy effort.\nUse your judgement on the reps. Great athletes will make each set a challenge and\nexecute the movements with great control and technique.\n\nMax heart rates are readily available here. For you fighters, this is a fight.\n\nBike a fast mile\nSit-ups\nBack extension\nMax set of pull-ups\nBench press @ body weight\nUpright row @ 1/3 body weight\nPush-ups\n\n\"Life is too short to waste. Dreams are fulfilled only through action,\nnot through endless planning to take action.\"\n~ David J. Schwartz\n\nHere is a handy rowing machine (ergometer) score calculator:\nhttp://users.ox.ac.uk/~quarrell/ergjava.html"
  },
  {
    "date": "2001-05-11",
    "text": "Three rounds for time of:\nRow 500 meters\nBack extension/sit-up, high rep\nDeadlift 5 reps\nRest\n\n\"There will always be a sacrifice required for results. It is the early bird\nwho gives up sleeping in to get the worm. To get what you want, right\non the heels of deciding what that is, you must also decide what you will\ndo in exchange for the results you desire.\"\n- James Ball\n\nThis is our second article by Dave Tate on squatting. This one gives some\naspects of the \"box squat\". Use of the \"box squat\" has been one of the\nbest advances our program has undertaken.\nhttp://t-mag.com/html/body_120squat.html. \nI hope it's obvious that we think this is important"
  },
  {
    "date": "2001-05-12",
    "text": "Five rounds for time of:\n25 Squats\n10 Pull-ups\n10 Dips\n\nSubmit time and level of assistance for pull-ups and dips.\n If assisted, keep assistance at same level throughout workout.\nTotal time and assistance amount is excellent indicator of your overall fitness.\nRush through!\n\n\"Every athlete who doesn't deadlift is yet to begin serious strength and conditioning.\nThere's no compromise on this. Everyone deadlifts!\"\n- Coach Glassman\n\nSpeaking of deadlifting, here is a primer on the subject:\nhttp://members.nbci.com/JackiePower/deadlift.htm"
  },
  {
    "date": "2001-05-13",
    "text": "Rest Day\n\n\"There is one thing stronger than all the armies in the world,\nand that is an idea whose time has come.\"\n~ Victor Hugo ~\n(1802-1885, French Poet, Dramatist, Novelist)\nHe was talking about CrossFit.\n\nLouie Simmons on Bench Press:\nhttp://www.deepsquatter.com/strength/archives/ls10.htm"
  },
  {
    "date": "2001-05-14",
    "text": "Five sets of Dips. Total the five sets. Then...\n\nThree rotations for time of:\nSnatch 1/3 body weight, 10 reps\nPowerclean 1/3 body weight, 10 reps\n20\" box jump, 15 reps\n\n\"In the sweat of thy face shalt thou eat bread.\"\nGenesis 3:19\n\nThe York Barbell Company is the oldest and most respected of American\nweightlifting equipment manufacturers. Their equipment is beautiful. They\npublish a quarterly journal on weightlifting that is always worth perusing.\nhttp://www.yorkbarbell.com/sh_winter2001.pdf"
  },
  {
    "date": "2001-05-15",
    "text": "5 Sets of pull-ups. Fast-slow-fast-slow-fast.\nThe fast ones are fast and sloppy; the slow ones are excruciatingly perfect.\nThis is, of course, high rep and low rep, alternating.\n\nThe following circuit contains three elements and is a powerful whole body workout.\nEach element is 45 seconds with a fifteen second rotation\n(not one second more or you start over).\n\nMake five rotations. That's exactly fifteen minutes.\nIf you don't know the elements you haven't been paying attention.\n(It's partly our fault; we're working on a page of descriptions and illustrations.)\n\nEmail us for details if you can't find them off of the archived routines and links.\n\"Wall Ball\"\nHollow Rock\nRomanian Deadlift/Upright Row combo movement\n\n\"I feel discombobulated.\"\n- BJ Penn\n\nGymnasts make easy work of other athlete's ab routines. We want to take\nfrom them all we can. Over time master each of these movements. Here is\nUSA Gymnastics on sit-up progressions:\nhttp://www.usagymnastics.org"
  },
  {
    "date": "2001-05-16",
    "text": "2000 meter row.\nEstablish PR (personal record) if able.\n\nThree rounds for time of:\n20 Powerclean\n20 Walking Lunges\n20Push-ups\n\n\"Never doubt that a small group of thoughtful, committed citizens can\nchange the world. Indeed, it is the only thing that ever has.\"\n- Margaret Mead\n\n\"There is one thing stronger than all the armies in the world, and that is\nan idea whose time has come.\"\n- Victor Hugo\n\nVern Gambetta knows the value of functional exercise. Check this article out.\nhttp://www.gambetta.com/articles/a97004.html"
  },
  {
    "date": "2001-05-17",
    "text": "Squat, 10\" box, with weight 20-10-5-3-1\n\nThree rounds each for time of:\nThree minute stand on bike at 70 rpm\nTwice up the rope (rope climb)\nTwenty sit-ups\nFifteen back extensions\n\n\"We may affirm absolutely that nothing great in the world has ever been\naccomplished without passion.\"\n- George Hegel\n\nWe've included this link for the odd gem found deep within its bowels.\nYou have to search but there is always a good post in one of the forums.\nhttp://www.sportspecific.com/"
  },
  {
    "date": "2001-05-18",
    "text": "Bench press 10-8-6-4-2 reps.\nTotal weight for all five sets and submit with body weight.\nRest as needed before,\n\nHow many passes of this circuit can you make in 20 minutes?\nCount each element (Box jump, Muscle-up, Leg raise) as a single point,\nso that, for instance, four complete circuits and once more 20 box jumps\nand one more muscle-up would be 14 points. If you still can't do the\nmuscle-up substitute twenty assisted pull-up and dips.\n\nBox Jump 20\" X 20 jumps\nMuscle-up\nHanging leg raise, toes to bar X10\n\n\"The belief that you can develop great musculature with isolation movements\nand without steroids is the bodybuilders pipe dream.\"\nCoach Glassman\n\nFor you coaches, Dr. Cornelius maintains that when analyzing athletic movement\n\"exact or precise points of muscle attachments and the technical names for these\nlocations are not essential; in fact, only the line of action is needed. Consequently,\na mental image of the muscle location and line of action is quite useful.\" This is of\nparticular interest to CrossFit because we've long maintained that what wasn't\nunderstood about human biomechanics could typically be explained via stick figures\nand vector force diagrams.\nhttp://www.usa-gymnastics.org/publications/technique/1997/1/muscular-force.html"
  },
  {
    "date": "2001-05-19",
    "text": "Powerclean 3X10-10-10 (Three sets of 10 reps).\nRest as needed before...\n\nComplete as many rounds in 20 minutes as you can of:\nRope climb\n15 Sit-ups\n10 Thrusters off 10\" box with dumbbells totaling 30% of your weight\n15 Back extensions\n\nGive one point for each exercise completed.\n\n\"It is a poor sport that is not worth the candle.\"\nGeorge Herbert (1593-1633)\n\nHuman Kinetics publishes an enormous amount of the serious\nliterature on exercise science. (Caution: the good and bad)\nhttp://www.humankinetics.com/\n\nHere is, for example, a cool product from Human Kinetics, The Interactive Hip:\nhttp://www.humankinetics.com"
  },
  {
    "date": "2001-05-20",
    "text": "Rest Day\n\n\"There is never a better measure of what a person is than what\nhe does when he's absolutely free to choose.\"\n- William Bulger\n\nYou needn't find a beam, but tape off some mat area and play with\nthe following balance/handstand drills. (hint, applicable to parallettes)\n\nhttp://www.usa-gymnastics.org/publications/technique/1996/5/handstand.html"
  }
];

window.MONTH_ARCHIVES = ['2001/02','2001/03','2001/04','2001/05'];
